# Generated by Django 4.0.4 on 2022-05-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='uploads/')),
                ('TIT2', models.CharField(blank=True, max_length=50, null=True)),
                ('TOPE', models.CharField(blank=True, max_length=50, null=True)),
                ('TALB', models.CharField(blank=True, max_length=50, null=True)),
                ('TOWN', models.CharField(blank=True, max_length=50, null=True)),
                ('TORY', models.CharField(blank=True, max_length=50, null=True)),
                ('TBPM', models.CharField(blank=True, max_length=50, null=True)),
                ('TSSE', models.CharField(blank=True, max_length=50, null=True)),
                ('TCON', models.CharField(blank=True, max_length=50, null=True)),
                ('TCOM', models.CharField(blank=True, max_length=50, null=True)),
                ('TCOP', models.CharField(blank=True, max_length=50, null=True)),
                ('TIPL', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
