# Generated by Django 4.0.4 on 2022-05-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='TALB',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='TIPL',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
