# Generated by Django 4.0.4 on 2022-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_audio_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='media',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
