# Generated by Django 4.0.4 on 2022-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_audio_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='org_file_name',
            new_name='id3_album',
        ),
        migrations.AddField(
            model_name='audio',
            name='id3_artist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='id3_bpm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='id3_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='id3_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='id3_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
