# Generated by Django 4.0.4 on 2022-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_org_file_name_audio_id3_album_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='id3_album',
            new_name='TALB',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='id3_artist',
            new_name='TBPM',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='id3_bpm',
            new_name='TIT2',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='id3_owner',
            new_name='TOPE',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='id3_title',
            new_name='TORY',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='id3_year',
            new_name='TOWN',
        ),
        migrations.AddField(
            model_name='audio',
            name='TSSE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
