# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_id3_album_audio_talb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='TCOM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='TCON',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
