# Generated by Django 4.0.4 on 2022-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_audio_tcom_audio_tcon'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='TCOP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='TIPL',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
