# Generated by Django 4.0.4 on 2022-05-25 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_audio_tcop_audio_tipl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
